sudo: required
jdk:
  - oraclejdk8
install:
  - mkdir -p $HOME/.cc-jars
  - wget -O howlci.jar https://dl.bintray.com/squiddev/maven/org/squiddev/howl.ci/0.1.9/howl.ci-0.1.9.jar
  - wget -O Howl.min.lua https://gist.githubusercontent.com/SquidDev/703e2f46ce68c2ca158673ff0ec4208c/raw/08ae237ec46a0b0e33b1385c6de852842d9b3abb/Howl.min.lua
cache:
  directories:
  - $HOME/.cc-jars
env:
  - CC_VERSION=1.79 CC_URL=https://addons-origin.cursecdn.com/files/2291/384/ComputerCraft1.79.jar
  - CC_VERSION=1.75 CC_URL=https://addons-origin.cursecdn.com/files/2269/339/ComputerCraft1.75.jar
  - CC_VERSION=1.8pr0-build0 CC_URL=http://crzd.me/files/maven/dan200/computercraft/ComputerCraft/1.80pr0-build0/ComputerCraft-1.80pr0-build0.jar
  #- CC_VERSION=1.64 CC_URL=https://minecraft.curseforge.com/projects/computercraft/files/2215320/download
  #- CC_VERSION=1.80pr0 CC_URL=https://minecraft.curseforge.com/projects/computercraft/files/2311039/download
  
script:
  - java -jar howlci.jar
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b1e44484ae6038503bd9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
